[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
include_trailing_comma = true
multi_line_output = 3
skip_glob = ["docs/*"]
